---
title: "Detect associations with a simulated quantitative trait"
#author:
output:
  #rmdformats::html_clean:
  rmdformats::downcute:
    downcute_theme: "chaos"
    use_bookdown: false
    self_contained: true
    thumbnails: true
    lightbox: true
    highlight: tango
    gallery: true
    toc_depth: 3
    #code_folding: show
    css: css/custom.css
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "html") })
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction

In this we are going to detect associations between genetic information and one or more quantitative traits.
We will be using simulated data, with a simple relationship beteween genotype and phenotype. To see how this same analysis is done with more messy data, see the "test_assoc_qt" vignette on [https://github.com/richelbilderbeek/plinkr](https://github.com/richelbilderbeek/plinkr/blob/master/vignettes/test_assoc_qt.Rmd)
```{r setup}
library(plinkr)
```
