---
title: "Exploratory data analysis and PCA"
#author:
output:
  #rmdformats::html_clean:
  rmdformats::downcute:
    downcute_theme: "chaos"
    use_bookdown: false
    self_contained: true
    thumbnails: true
    lightbox: true
    highlight: tango
    gallery: true
    toc_depth: 3
    code_folding: show
    css: css/custom.css
knit:
  (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding =
  encoding, output_dir = "html") })
---

```{r}
rm(list = ls())
getwd()
list.files()
```

We start from the data after QC of the file `2_QC_plink.Rmd`.

We compute the IBS (Identity-By-State) distance between individuals.
Not Euclidean distances!
```{r}
system("plink \\
--chr-set 29 no-xy \\
--allow-no-sex \\
--nonfounders \\
--file Data/ADAPTmap_genotypeTOP_20160222_full/out/ADAPTmap_TOP \\
--distance-matrix \\
--out Data/ADAPTmap_genotypeTOP_20160222_full/out/PCA_data")
```

### Load distance matrix

```{r}
dist_matrix <- read.table("Data/ADAPTmap_genotypeTOP_20160222_full/out/PCA_data.mdist", header = F)
head(dist_matrix)
# Extract breeds names
fam <- data.frame(famids = read.table("Data/ADAPTmap_genotypeTOP_20160222_full/out/PCA_data.mdist.id")[, 1])
head(fam)
# Extract individual names
famInd <- data.frame(IID = read.table("Data/ADAPTmap_genotypeTOP_20160222_full/out/PCA_data.mdist.id")[, 2])
head(famInd)
```
And Multidimensional scaling (MDS/PCoA) on the distance matrix of the dataset.
#### With `cmdscale()`
```{r}
mds_pop <- cmdscale(dist(dist_matrix), eig = TRUE, 6)
head(mds_pop)
```
```{r}
nrow(fam)
nrow(famInd)
nrow(mds_pop$points)

eigenvec_populations <- cbind(fam, famInd, mds_pop$points)
head(eigenvec_populations)
eigen_percent <- round(((mds_pop$eig) / sum(mds_pop$eig)) * 100, 2)
```
We have calculated the Eigenvectors and Eigenvalues.
```{r}
library(tidyverse)
eigenvec_populations %>%
  ggplot(aes(., x = `1`, y = `2`, color = famids)) +
  geom_point() +
  theme_bw()
```

